### ISSUE TITLE
Drivetime intervals near water

### ISSUE THREAD

**Issue by matias-piin** [urbica/galton#180]
Hi,
I'm finding that drivetimes generated near large bodies of water with multiple intervals cause some weird behavior. That is the intervals are not supersets of each other.

Example:
https://galton.urbica.co/?&ll=-122.50264045111601,37.748018657001396&zoom=11.8&city=san-francisco&mode=car&page=cities&lang=en&center=11.8

When asking for a single interval (the larger one) it correctly returns a shape that would cover the smaller one, but when asked for all intervals at once you get these non-overlapping shapes.

Is there a way to fix this?

**Comment by glifchits** [comment]
This issue should be closed now that Galton has the latest version of the isochrones library
