### ISSUE TITLE
Nodejs v6 no longer supported by OSRM

### ISSUE THREAD

**Issue by MichielDeMey** [urbica/galton#200]
I briefly looked into upgrading the OSRM module for this project and it seems they dropped support for Nodejs v6 since OSRM 5.16.0, updated the OSRM module to 5.16.4 and bumped the Nodejs version to v8 on my branch and works like a charm.

Commit:
https://github.com/MichielDeMey/galton/commit/da199de0490fb334b351b885a2bef6a850b0102e

Build:
https://travis-ci.org/MichielDeMey/galton/builds/360972031

Not saying you should upgrade right away, but something to take into account going forward.

**Comment by stepankuzmin** [comment]
Thanks for the issue, @MichielDeMey!

I've updated OSRM dependency to 5.16.4 and published new Galton version v5.16.4.
