### ISSUE TITLE
An option should exist to specify the "intervals" in the request 

### ISSUE THREAD

**Issue by snario** [urbica/galton#32]
I think it is natural to want to allow users to make requests like

`/?lat=43&lng=-122&time=5`

or perhaps use `intervals` and pass in an array.

**Comment by stepankuzmin** [comment]
Hi there, @snario! You can do that by passing options with request
https://github.com/urbica/galton/blob/master/examples/index.html#L117

For defining time intervals you can use `intervals[]` option.

**Comment by snario** [comment]
This does not work when the array is of length 1, e.g.,

```js
$.getJSON('http://127.0.0.1:4000', {lat: 41.38, lng: 2.193, intervals: [1]})
```

It uses the server defaults in this case.

**Comment by stepankuzmin** [comment]
Which version do you use?

`galton -v`

**Comment by snario** [comment]
Right now I am using 1.2.2

**Comment by stepankuzmin** [comment]
You should update to the latest version.

**Comment by snario** [comment]
Hi @stepankuzmin I upgraded to v1.2.6 (the latest on `npm`) and unfortunately it is still broken. Does 1.2.7 fix this particular issue?

**Comment by stepankuzmin** [comment]
Hi there! I think you should update to `galton@1.2.8`. Unfortunately I can't reproduce this issue. If the problem is still there, please reopen this issue.
